name: build 
on: [push, pull_request]

jobs:
  buildupload:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: dotNET Core
        uses: actions/setup-dotnet@v1

      - name: Build
        run: dotnet build --configuration Release -o .
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ezSig.exe
          path: ezSig.exe
        


